# Site settings
title: Mike Carter &bull; Software Architect
email: mike@mcarter.me
description: >
  I'm Mike Carter, I work as a Software Architect at Holiday Extras in sunny Kent, UK.
  I also do contracting work through my own small company, Leaf.
description_html: >
  I'm Mike Carter, I work as a Software Architect at <a href="http://holidayextras.com">Holiday Extras</a> in sunny Kent, UK.
  I also do contracting work through my own small company, <a href="http://www.weareleaf.com">Leaf</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mcarter.me" # the base hostname & protocol for your site
twitter_username: mcarterj
github_username:  michaelcarter

# Build settings
markdown: kramdown
